version: '3.8'

services:
  postgres:
    image: postgres
    container_name: users
    restart: always
    environment:
      POSTGRES_PASSWORD: Qwerty123!
    ports:
      - 5433:5432
  hillel-api:
    build: .
    container_name: hillel-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Qwerty123!
    ports:
      - 8080:8080
    depends_on:
      - postgres