version: '3.8'

services:
  users:
    image: postgres
    container_name: users
    restart: always
    environment:
      POSTGRES_PASSWORD: Qwerty123!
    ports:
      - 5432:5432
  hillel-api:
    build: .
    container_name: hillel-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://users:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Qwerty123!
    ports:
      - 8082:8082
    depends_on:
      - users
      - kafka-ui
  mail-api:
      build: ../mail
      container_name: mail-api
      ports:
        - 8081:8081
      depends_on:
        - hillel-api
  zookeeper:
        image: bitnami/zookeeper:latest
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
        image: bitnami/kafka:latest
        ports:
          - 9094:9094
        depends_on:
          - zookeeper
        environment:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
          KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  kafka-ui:
        image: provectuslabs/kafka-ui:latest
        ports:
          - 8080:8080
        environment:
          - KAFKA_CLUSTERS_0_NAME=local
          - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        depends_on:
          - kafka

#  sonarqube:
#        image: sonarqube:community
#        volumes:
#          - sonarqube_data:/opt/sonarqube/data
#          - sonarqube_extensions:/opt/sonarqube/extensions
#          - sonarqube_logs:/opt/sonarqube/logs
#        ports:
#          - "9000:9000"
#  volumes:
#      project_data:
#      sonarqube_data:
#      sonarqube_extensions:
#      sonarqube_logs: